# Generated by Django 5.2.5 on 2025-08-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listing_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="identifier",
            field=models.CharField(default="8XWXG", max_length=5),
        ),
    ]
