# Generated by Django 4.0.6 on 2025-09-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='identifier',
            field=models.CharField(default='RFT0I', max_length=5),
        ),
    ]
